backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\Event;
use common\models\EventVolunteer;
use common\models\search\EventSearch;
use common\models\search\EventVolunteerSearch;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','get-data-event','get-data-volunteer'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
	
	public function actionGetDataEvent($start,$end)
	{
		$searchModel = new EventSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$dataProvider->query->where(['is_deleted'=>0]);
		$dataProvider->query->andWhere(['between','date(waktu_keputusan_admin)',$start,$end]);
		$dataProvider->query->andWhere(['status'=>1]);
		
        return $this->renderAjax('_event',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
	}
	
	public function actionGetDataVolunteer($start,$end)
	{
		$searchModel = new EventVolunteerSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$dataProvider->query->andWhere(['between','date(waktu_keputusan_admin)',$start,$end]);
		$dataProvider->query->andWhere(['status'=>1]);
		
        return $this->renderAjax('_event_volunteer',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
	}
    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\Event;
use common\models\News;
use common\models\Role;
use common\models\User;
use common\models\HubungiKami;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
		$limitEvent = Event::find()->where(['is_deleted'=>0,'status'=>1])->limit('6')->orderBy(['id' => SORT_DESC])->all();
		$limitNews1 = News::find()->where(['is_deleted'=>0])->limit('1')->orderBy(['id' => SORT_DESC])->all();
		$limitNews2 = News::find()->where(['is_deleted'=>0])->limit('2')->orderBy(['id' => SORT_DESC])->offset('1')->all();
        return $this->render('index',[
			'limitEvent'=>$limitEvent,
			'limitNews1'=>$limitNews1,
			'limitNews2'=>$limitNews2,
		]);
    }
	
	public function actionBantuan()
    {
		date_default_timezone_set("Asia/Jakarta");
		$model = new HubungiKami();
		$model->created_at=date("Y-m-d H:i:s");
		if ($model->load(Yii::$app->request->post())){
			$model->save();
			Yii::$app->session->setFlash('success', 'Terima Kasih Sudah Mengirim Pesan.');
            return $this->redirect(['bantuan']);
        }
		
        return $this->render('bantuan',[
			'model'=>$model,
		]);
    }

    public function actionAcara()
    {
        return $this->render('acara');
    }

    public function actionBerita()
    {
        return $this->render('berita');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
		//$this->layout = 'main-login';
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/account']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->redirect(['/account']);
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
	
	public function actionGetLoadMoreEvent($row,$user_id)
	{
		$data=Event::find()->where(['user_id'=>$user_id])->limit($row)->all();
		
		
        return $this->renderAjax('get-load-more-event', [
            'data' => $data,
			'row'=>$row,
        ]);
	}

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(['/']);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
		date_default_timezone_set("Asia/Jakarta");
        $model = new User();
		$model->status = 1;
		$model->role_id = Role::VOLUNTEER;
		$model->is_deleted = 0;
		$model->created_at=date("Y-m-d H:i:s");
		$model->foto='default_user.png';
        if ($model->load(Yii::$app->request->post())) {
			if($_FILES['foto']['name']!=''){				
				$foto=$_FILES['foto'];
				$arr = explode(".", $foto['name']);
				$extension = end($arr);

				# generate a unique file name
				$model->foto = "featured_" . date("Y_m_d_H_i_s_") . \Yii::$app->security->generateRandomString(4) . "." . $extension;

				# the path to save file
				$path = \Yii::getAlias("@frontend/web/uploads/") . $model->foto;
				move_uploaded_file($foto['tmp_name'], $path);
				
				//resize image
				//$image = new ImageResize($path);
				//$image->resizeToLongSide(683);
				//$image->save($path);
			}
			
			
			$user=$_POST['User'];
			if($user['email']=='' || $user['username']=='' || $user['password']=='' || $user['nama_lengkap']=='' || $user['no_identitas']=='' || $user['tempat_lahir']=='' || $user['tanggal_lahir']=='' || $user['jenis_kelamin']=='' || $user['no_telp']=='' || $user['alamat_lengkap']==''){
				\Yii::$app->session->addFlash("danger", "kolom tidak boleh kosong, harap periksa kembali");
			}else{
				$model->password=md5($model->password);
				$model->save();
				return $this->redirect(['login']);
				Yii::$app->session->setFlash('success', 'Pendaftaran Berhasil.');
			}
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }
}

backend/views/site/_event.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\EventVolunteer;
/* @var $this yii\web\View */
/* @var $searchModel common\models\search\EventSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>
<div class="box box-info">
	<div class="box-header"><h3>Data Event</h3><hr/></div>
    <div class="box-body">
		<?= GridView::widget([
			'layout' => '{summary}{pager}{items}{pager}',
			'dataProvider' => $dataProvider,
			'pager' => [
				'class' => yii\widgets\LinkPager::className(),
				'firstPageLabel' => 'First',
				'lastPageLabel' => 'Last'],
		//	'filterModel' => $searchModel,
			'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
			'headerRowOptions' => ['class' => 'x'],
			'columns' => [
				[
					'class' => 'yii\grid\SerialColumn',
					'contentOptions' => ['nowrap' => 'nowrap', 'style' => 'text-align:center;width:50px']
				],
				'nama',
				[
					'class' => yii\grid\DataColumn::className(),
					'attribute' => 'created_by',
					'label'=>'Created By',
					'value' => function ($model) {
						return $model->user->nama_lengkap;
					},
				],
				[
					'class' => yii\grid\DataColumn::className(),
					'attribute' => '',
					'label'=>'',
					'value' => function ($model) {						
						return Html::a("Detail Event", ["/event/view", "id" => $model->id], ["class" => "btn btn-success", "title" => "Detail"]);
					},
					'format' => 'raw',
				],
				[
					'class' => yii\grid\DataColumn::className(),
					'attribute' => '',
					'label'=>'',
					'value' => function ($model) {
						$countVolunteer = EventVolunteer::find()->where(['event_id'=>$model->id,'status'=>0])->count();
						if($countVolunteer>0){								
							return Html::a($countVolunteer." Volunteer Menunggu Konfirmasi", ["/event/list-volunteer", "id" => $model->id], ["class" => "btn btn-primary", "title" => "Detail"]);
						}else{
							return Html::a("<i class='fa fa-list'></i>", ["/event/list-volunteer", "id" => $model->id], ["class" => "btn btn-primary", "title" => "Detail"]);
						}
					},
					'format' => 'raw',
				],
			],
		]); ?>
	</div>
</div>

backend/views/site/_event_volunteer.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\EventVolunteer;
/* @var $this yii\web\View */
/* @var $searchModel common\models\search\EventSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>
<div class="box box-info">
	<div class="box-header"><h3>Data Volunteer</h3><hr/></div>
    <div class="box-body">
		<?= GridView::widget([
			'layout' => '{summary}{pager}{items}{pager}',
			'dataProvider' => $dataProvider,
			'pager' => [
				'class' => yii\widgets\LinkPager::className(),
				'firstPageLabel' => 'First',
				'lastPageLabel' => 'Last'],
		//	'filterModel' => $searchModel,
			'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
			'headerRowOptions' => ['class' => 'x'],
			'columns' => [
				[
					'class' => 'yii\grid\SerialColumn',
					'contentOptions' => ['nowrap' => 'nowrap', 'style' => 'text-align:center;width:50px']
				],
				[
					'class' => yii\grid\DataColumn::className(),
					'attribute' => 'volunteer',
					'label'=>'Volunteer',
					'value' => function ($model) {
						return $model->user->nama_lengkap;
					},
				],
				[
					'class' => yii\grid\DataColumn::className(),
					'attribute' => 'event',
					'label'=>'Event',
					'value' => function ($model) {
						return $model->event->nama;
					},
				],
			],
		]); ?>
	</div>
</div>

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fas fa-exclamation text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a> or try using the search
                form.
            </p>

            <form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

backend/views/site/index.php
<?php

use common\models\Event;
use common\models\EventVolunteer;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
date_default_timezone_set('Asia/Jakarta'); 
$this->title = 'Beranda';

if(isset($_GET['start'])){	
	$start = $_GET['start'];
}
if (!isset($start)) {
    $start = date("Y-m-d",strtotime("-1 months"));
}

if(isset($_GET['end'])){	
	$end = $_GET['end'];
}
if (!isset($end)) {
    $end = date("Y-m-d");
}


?>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <div class="row" style="margin-bottom: 20px">
                    <div class="col-md-2">
                        <?= Html::textInput("start_date", $start, ["value"=>$start,"type" => "date", "class" => "form-control", "id" => "start_date"]) ?>
                    </div>
                    <div class="col-md-2">
                        <?= Html::textInput("end_date", $end, ["value"=>$end,"type" => "date", "class" => "form-control", "id" => "end_date"]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="box">
			<div class="box-header"><h3>Jumlah Event</h3><hr/></div>
            <div class="box-body">
                <div id="container" style="height: 400px; margin: 0 auto"></div>
            </div>
        </div>
    </div>
	<div class="col-md-6">
        <div class="box">
			<div class="box-header"><h3>Jumlah Volunter Bergabung</h3><hr/></div>
            <div class="box-body">
                <div id="container2" style="height: 400px; margin: 0 auto"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
		<div id="output"></div>
    </div>
	<div class="col-md-12">
		<div id="output2"></div>
    </div>
</div>
<?php
$tanggal = [];
$tanggalDisplay = [];
for ($i = strtotime($start); $i <= strtotime($end); $i += 3600 * 24) {
    $tanggal[] = date("Y-m-d", $i);
    $tanggalDisplay[] = date("d M", $i);
}

$webVisit = [];
$pageVisit = [];
foreach ($tanggal as $tgl) {
    $webVisit[] = intval(Event::find()->where(['status'=>1])->andWhere(['between','date(waktu_keputusan_admin)',$start,$tgl])->count());
    $volunteerJoin[] = intval(EventVolunteer::find()->where(['status'=>1])->andWhere(['between','date(waktu_keputusan_admin)',$start,$tgl])->count());
}
?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $("#start_date").change(function () {
        window.location = "<?= Url::to(["site/index"]) ?>?start=" + $("#start_date").val() + "&end=" + $("#end_date").val();
		$("#output").load("<?= Url::to(['site/get-data-event']) ?>?start=" + $("#start_date").val()+ "&end=" + $("#end_date").val());
		$("#output2").load("<?= Url::to(['site/get-data-volunteer']) ?>?start=" + $("#start_date").val()+ "&end=" + $("#end_date").val());
		return false;
    });
    $("#end_date").change(function () {
        window.location = "<?= Url::to(["site/index"]) ?>?start=" + $("#start_date").val() + "&end=" + $("#end_date").val();
		$("#output").load("<?= Url::to(['site/get-data-event']) ?>?start=" + $("#start_date").val()+ "&end=" + $("#end_date").val());
		$("#output2").load("<?= Url::to(['site/get-data-volunteer']) ?>?start=" + $("#start_date").val()+ "&end=" + $("#end_date").val());
        return false;
    });

    $(document).ready(function () {
        Highcharts.chart('container', {
            chart: {
                type: 'line'
            },
            title: {
                text: ''
            },
            xAxis: {
                categories: <?= \yii\helpers\Json::encode($tanggalDisplay) ?>
            },
            credits: {
                enabled: false
            },
            series: [{
                name: 'Jumlah Event',
                data:  <?= \yii\helpers\Json::encode($webVisit) ?>
            }]
        });
		
		Highcharts.chart('container2', {
            chart: {
                type: 'line'
            },
            title: {
                text: ''
            },
            xAxis: {
                categories: <?= \yii\helpers\Json::encode($tanggalDisplay) ?>
            },
            credits: {
                enabled: false
            },
            series: [{
                name: 'Jumlah Volunter Bergabung',
                data:  <?= \yii\helpers\Json::encode($volunteerJoin) ?>
            }]
        });
		$("#output").load("<?= Url::to(['site/get-data-event']) ?>?start=" + $("#start_date").val()+ "&end=" + $("#end_date").val());
		$("#output2").load("<?= Url::to(['site/get-data-volunteer']) ?>?start=" + $("#start_date").val()+ "&end=" + $("#end_date").val());
    });
</script>

backend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Cabang;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<style>
    .login-page, .register-page {
        background: url("<?= \yii\helpers\Url::to(["/css/images/login-background.jpg"]) ?>") no-repeat center center fixed !important;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
</style>

<div class="col-md-3" id="sidebar" style="background: rgb(255, 255, 255); padding: 166px 40px 0px; height: 664px;">
    <img class="img img-responsive" src="<?= \yii\helpers\Url::to(["/css/images/volunteerku-logo.png"]) ?>" alt="">
    <hr>
    <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

    <?= $form
        ->field($model, 'username', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

    <?= $form
        ->field($model, 'password', $fieldOptions2)
        ->label(false)
        ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

    <div class="row">
        <div class="col-xs-8">
            <?= $form->field($model, 'rememberMe')->checkbox() ?>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
            <?= Html::submitButton('Sign in', ['class' => 'btn btn-info btn-block', 'name' => 'login-button']) ?>
        </div>
        <!-- /.col -->
    </div>


    <?php ActiveForm::end(); ?>
</div>

<?php $this->registerJs('

$("#sidebar").height($(window).height()-166);


');