backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\Event;
use common\models\EventVolunteer;
use common\models\search\EventSearch;
use common\models\search\EventVolunteerSearch;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','get-data-event','get-data-volunteer'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
	
	public function actionGetDataEvent($start,$end)
	{
		$searchModel = new EventSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$dataProvider->query->where(['is_deleted'=>0]);
		$dataProvider->query->andWhere(['between','date(waktu_keputusan_admin)',$start,$end]);
		$dataProvider->query->andWhere(['status'=>1]);
		
        return $this->renderAjax('_event',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
	}
	
	public function actionGetDataVolunteer($start,$end)
	{
		$searchModel = new EventVolunteerSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$dataProvider->query->andWhere(['between','date(waktu_keputusan_admin)',$start,$end]);
		$dataProvider->query->andWhere(['status'=>1]);
		
        return $this->renderAjax('_event_volunteer',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
	}
    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\Event;
use common\models\News;
use common\models\Role;
use common\models\User;
use common\models\HubungiKami;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
		$limitEvent = Event::find()->where(['is_deleted'=>0,'status'=>1])->limit('6')->orderBy(['id' => SORT_DESC])->all();
		$limitNews1 = News::find()->where(['is_deleted'=>0])->limit('1')->orderBy(['id' => SORT_DESC])->all();
		$limitNews2 = News::find()->where(['is_deleted'=>0])->limit('2')->orderBy(['id' => SORT_DESC])->offset('1')->all();
        return $this->render('index',[
			'limitEvent'=>$limitEvent,
			'limitNews1'=>$limitNews1,
			'limitNews2'=>$limitNews2,
		]);
    }
	
	public function actionBantuan()
    {
		date_default_timezone_set("Asia/Jakarta");
		$model = new HubungiKami();
		$model->created_at=date("Y-m-d H:i:s");
		if ($model->load(Yii::$app->request->post())){
			$model->save();
			Yii::$app->session->setFlash('success', 'Terima Kasih Sudah Mengirim Pesan.');
            return $this->redirect(['bantuan']);
        }
		
        return $this->render('bantuan',[
			'model'=>$model,
		]);
    }

    public function actionAcara()
    {
        return $this->render('acara');
    }

    public function actionBerita()
    {
        return $this->render('berita');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
		//$this->layout = 'main-login';
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/account']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->redirect(['/account']);
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
	
	public function actionGetLoadMoreEvent($row,$user_id)
	{
		$data=Event::find()->where(['user_id'=>$user_id])->limit($row)->all();
		
		
        return $this->renderAjax('get-load-more-event', [
            'data' => $data,
			'row'=>$row,
        ]);
	}

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(['/']);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
		date_default_timezone_set("Asia/Jakarta");
        $model = new User();
		$model->status = 1;
		$model->role_id = Role::VOLUNTEER;
		$model->is_deleted = 0;
		$model->created_at=date("Y-m-d H:i:s");
		$model->foto='default_user.png';
        if ($model->load(Yii::$app->request->post())) {
			if($_FILES['foto']['name']!=''){				
				$foto=$_FILES['foto'];
				$arr = explode(".", $foto['name']);
				$extension = end($arr);

				# generate a unique file name
				$model->foto = "featured_" . date("Y_m_d_H_i_s_") . \Yii::$app->security->generateRandomString(4) . "." . $extension;

				# the path to save file
				$path = \Yii::getAlias("@frontend/web/uploads/") . $model->foto;
				move_uploaded_file($foto['tmp_name'], $path);
				
				//resize image
				//$image = new ImageResize($path);
				//$image->resizeToLongSide(683);
				//$image->save($path);
			}
			
			
			$user=$_POST['User'];
			if($user['email']=='' || $user['username']=='' || $user['password']=='' || $user['nama_lengkap']=='' || $user['no_identitas']=='' || $user['tempat_lahir']=='' || $user['tanggal_lahir']=='' || $user['jenis_kelamin']=='' || $user['no_telp']=='' || $user['alamat_lengkap']==''){
				\Yii::$app->session->addFlash("danger", "kolom tidak boleh kosong, harap periksa kembali");
			}else{
				$model->password=md5($model->password);
				$model->save();
				return $this->redirect(['login']);
				Yii::$app->session->setFlash('success', 'Pendaftaran Berhasil.');
			}
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/acara.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Acara';
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-acara">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <!-- <code><?= __FILE__ ?></code> -->
</div>

frontend/views/site/bantuan.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use common\models\Faq;
/**
 * @var yii\web\View $this
 * @var common\models\Role $model
 * @var yii\widgets\ActiveForm $form
 */


$this->title = 'Bantuan';
?>
    <link href="<?= url::to(['OwlCarousel/dist/assets/owl.carousel.css']) ?>" rel="stylesheet" type="text/css">
    <link href="<?= url::to(['OwlCarousel/dist/assets/owl.theme.default.min.css']) ?> " rel="stylesheet" type="text/css">
    <style type="text/css">
      *{
        margin: 0;
        padding: 0;
      }
      .img-fluid{
        width: 100%;
        height:30%;
        display: block;
      }
	  #custom-search-input{
    padding: 3px;
    border: solid 1px #E4E4E4;
    border-radius: 6px;
    background-color: #fff;
	}

	#custom-search-input input{
		border: 0;
		box-shadow: none;
	}

	#custom-search-input button{
		margin: 2px 0 0 0;
		background: none;
		box-shadow: none;
		border: 0;
		color: #666666;
		padding: 0 8px 0 10px;
		border-left: solid 1px #ccc;
	}

	#custom-search-input button:hover{
		border: 0;
		box-shadow: none;
		border-left: solid 1px #ccc;
	}

	#custom-search-input .glyphicon-search{
		font-size: 23px;
	}
	
	h4{
		cursor:pointer;
	}
	.expand_caret {
		transform: scale(1.3);
		margin-left: 8px;
		margin-top: -4px;
	}
	h4[aria-expanded='false'] > .expand_caret {
		transform: scale(1.3) rotate(-180deg);
	}
	
    </style>
	<script src="<?= url::to(['OwlCarousel/docs/assets/vendors/jquery.min.js']) ?>" type="text/javascript"></script>
	  <script src="<?= url::to(['OwlCarousel/dist/owl.carousel.js']) ?>" type="text/javascript"></script>
	  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	  <script>
            $(document).ready(function() {
              var owl = $('.owl-carousel');
              owl.owlCarousel({
                items: 1,
                loop: true,
                margin: 10,
                autoplay: true,
                autoplayTimeout: 3000,
                //autoplayHoverPause: true
              });
            })
          </script>

<div class="site-index">
	<div class="container">
		<hr style="border-color:#fff;"/>
		<p style="font-size:30px;font-weight:600;text-transform:uppercase;">FAQ</p>
		<div class="row" style="margin:0;">
			<div class="col-lg-12" style="padding:0;">
				<div class="accordion" id="accordionExample">
					<?php
						$i=1;
						foreach(Faq::find()->where(['status'=>0])->all() as $faq){
							
					?>
							<div class="card">
								<div class="card-header" id="heading<?=$faq->id?>">
									<h4 class="mb-0" style="font-weight:bold;" data-toggle="collapse" data-target="#collapse<?=$faq->id?>" aria-expanded="<?=($i==1)?'true':'false'?>" aria-controls="collapse<?=$faq->id?>">
										<?=$faq->pertanyaan?>
										<span class="pull-right expand_caret"><i class="fas fa-chevron-up"></i></span>
									</h4>
								</div>

								<div id="collapse<?=$faq->id?>" class="collapse <?=($i==1)?'show':''?>" aria-labelledby="heading<?=$faq->id?>" data-parent="#accordionExample">
									<hr/>
									<div class="card-body">
										<p style="font-size:17px;">
											<?=$faq->jawaban?>
										</p>
									</div>
								</div>
								<hr/>
							</div>
					<?php 
							$i++;
						} 
					?>
					
				</div>
			</div>
		</div>
		<hr style="border-color:#fff;"/>
		<p style="font-size:30px;font-weight:600;text-transform:uppercase;">Hubungi Kami</p>
		<div class="row" style="margin:0;">
			<div class="box">
				<div class="col-md-offset-3 col-md-6">
					<?php $form = ActiveForm::begin([
							'id' => 'HubungiKami',
							'enableClientValidation' => false,
							'errorSummaryCssClass' => 'error-summary alert alert-error',
						]
					);
					?>
					<?= $form->field($model, 'nama')->textInput(['maxlength' => true])->label('Nama Lengkap') ?>
					<?= $form->field($model, 'no_telp')->textInput(['maxlength' => true])->label('No Telepon') ?>
					<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
					<?= $form->field($model, 'pesan')->textArea(['rows' => 6])->label('Pesan') ?>
					<hr/>
					<?php echo $form->errorSummary($model); ?>
					<div class="row" style="display:flex;justify-content:center;align-items:center;">
						<?= Html::submitButton('Kirim', ['class' => 'btn btn-danger', 'style'=>'display:block;background: #ff4444;color: #fff;padding: 5px 30px;text-transform: uppercase;font-weight: 600;font-size:16px;']); ?>
					</div>

					<?php ActiveForm::end(); ?>
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>
		<hr/>
	</div>
</div>

frontend/views/site/berita.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Berita';
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-bcara">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <!-- <code><?= __FILE__ ?></code> -->
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/profile.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use common\models\User;
/**
 * @var yii\web\View $this
 * @var common\models\Role $model
 * @var yii\widgets\ActiveForm $form
 */

$user=\Yii::$app->user->identity;
$this->title = 'Account';
?>
<?php $this->registerJs('

$(".load-more").on("click",function(){
	var row = Number($("#row").val());
    var allcount = Number($("#all").val());
    row = row + 4;
	
	if(row <= allcount){
		$("#row").val(row);
	$("#output").load("' . Url::to(["site/get-load-more-event"]) . '?row=" + row+"&user_id='.$user->id.'");
		if(row==allcount){
			$(".load-more").hide();
		}
	}else{
		$("#row").val(row);
	$("#output").load("' . Url::to(["site/get-load-more-event"]) . '?row=" + row+"&user_id='.$user->id.'");
		$(".load-more").hide();
	}
});


') ?>
    <link href="<?= url::to(['OwlCarousel/dist/assets/owl.carousel.css']) ?>" rel="stylesheet" type="text/css">
    <link href="<?= url::to(['OwlCarousel/dist/assets/owl.theme.default.min.css']) ?> " rel="stylesheet" type="text/css">
    <style type="text/css">
      *{
        margin: 0;
        padding: 0;
      }
      .img-fluid{
        width: 100%;
        height:30%;
        display: block;
      }
	  #custom-search-input{
    padding: 3px;
    border: solid 1px #E4E4E4;
    border-radius: 6px;
    background-color: #fff;
}

#custom-search-input input{
    border: 0;
    box-shadow: none;
}

#custom-search-input button{
    margin: 2px 0 0 0;
    background: none;
    box-shadow: none;
    border: 0;
    color: #666666;
    padding: 0 8px 0 10px;
    border-left: solid 1px #ccc;
}

#custom-search-input button:hover{
    border: 0;
    box-shadow: none;
    border-left: solid 1px #ccc;
}

#custom-search-input .glyphicon-search{
    font-size: 23px;
}
	  
    </style>
	<script src="<?= url::to(['OwlCarousel/docs/assets/vendors/jquery.min.js']) ?>" type="text/javascript"></script>
	  <script src="<?= url::to(['OwlCarousel/dist/owl.carousel.js']) ?>" type="text/javascript"></script>

	  <script>
            $(document).ready(function() {
              var owl = $('.owl-carousel');
              owl.owlCarousel({
                items: 1,
                loop: true,
                margin: 10,
                autoplay: true,
                autoplayTimeout: 3000,
                //autoplayHoverPause: true
              });
            })
          </script>

<div class="site-index">

    <div class="container" style="padding:20px;">
		<div style="min-height:400px;background-repeat: no-repeat;background-size: cover;height:500px;background-position:center;background-image:url(<?=Url::to(['image/compress/2.jpg'])?>);border:1px solid #eee;border-radius:20px;box-shadow:inset 0 0 0 2000px rgba(0, 0,0, 0.7);">
			<h1 style="color:#fff;">tes</h1>
		</div>
	<hr/>
    </div>
    <div class="body-content container">
		<h2>Event Saya</h2>
		<hr/>
		<div id="output">
			<div class="row">
				<div class="col-lg-3" style="padding:10px;">
					<a href="<?=Url::to(['/site/create-event'])?>" style="text-decoration:none;">
					<div style="border:2px dashed #000;min-height:200px;overflow:hidden;margin-top:10px;border-radius:10px;display:flex;background:#fff;padding:10px 20px;flex-direction:column;justify-content: center;align-items: center;padding:0 15px 0 0;vertical-align:center;">
								<i class="fa fa-plus" style="color:#999;font-size:36px;width:100%;"></i>
					</div>
					</a>
				</div>           
			   <?php foreach(common\models\Event::find()->where(['user_id'=>$user->id])->limit('3')->all() as $event){?>
				<div class="col-lg-3" style="padding:10px;">
					<a href="<?=Url::to(['/event/detail','id'=>$event->id])?>" style="text-decoration:none;">
						<div style="-webkit-box-shadow: 0px 0px 16px 1px rgba(0,0,0,0.21);-moz-box-shadow: 0px 0px 16px 1px rgba(0,0,0,0.21);box-shadow: 0px 0px 16px 1px rgba(0,0,0,0.21);min-height:250px;overflow:hidden;margin-top:10px;border-radius:10px;background-image:url(<?=Url::to(['/uploads/'.$event->foto])?>);background-size:cover;background-position:center;display:flex;flex-direction:column;">
							<div style="flex:1;"></div>
							<div style="display:flex;flex-direction:column;background:#fff;padding:10px;justify-content: flex-end;">
								<h4 style="color:#000;margin:0;font-weight:bold;padding:5px;"><?=$event->nama?></h4>
								<h5 style="color:#999;margin:0;font-weight:bold;padding:0 5px 0;"><?=date("d F Y",strtotime($event->mulai))?></h5>
							</div>
						</div>
					</a>
				</div>
				<?php }?>
			</div>
		</div>
		<?php if(common\models\Event::find()->where(['user_id'=>$user->id])->count()>3){?>
			<div class="row" style="padding-top:20px;display:flex;align-items:center;justify-content:center;">
				<button class="btn btn-default load-more" style="background: #ff4444;color: #fff;padding: 10px 30px;text-transform: uppercase;font-weight: 600;">Read More</button>
			</div>
			<hr/>
		<?php }elseif(common\models\Event::find()->where(['user_id'=>$user->id])->count()<=3){?>
			<hr/>
		<?php }?>
		<input type="hidden" id="row" value="4">
		<input type="hidden" id="all" value="<?=count(common\models\Event::find()->where(['user_id'=>$user->id])->all())?>">
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>